### ISSUE TITLE
[PE-D] Result window seems cluttered

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T11-3/tp#147]
Result window seems cluttered. Could space out the details. 
![Screenshot 2022-04-01 at 2.16.08 PM.png](https://raw.githubusercontent.com/rahulprasad01/ped/main/files/5d166320-544a-453c-a351-5824180d9c4d.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: rahulprasad01/ped#1

**Comment by lchokhoe** [comment]
"Good to fix" Bug.

Nothing app breaking. Will look into it low.priority.

Will look in to it after fixing issue #170
