### ISSUE TITLE
[PE-D] Misspelt `priority` in User Guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T11-3/tp#148]
The parameter `priority` is misspelt as `piroity` in the user guide.

![image.png](https://raw.githubusercontent.com/TypeDefinition/ped/main/files/0301b475-3c80-44d3-ac2f-843e5d539e53.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: TypeDefinition/ped#2

**Comment by lchokhoe** [comment]
Same as issue #161
