### ISSUE TITLE
[PE-D] finding name with spaces failed

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T11-3/tp#149]
**Bug**
- finding a name containing spaces show no result

**To reproduce**
- add an application `add n/Two names j/none p/12345678 e/a@gmail.com a/fake address`
- then run `find n/Two names`

**Expected behaviour**
- Show the application with name `Two names`

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: 1001mei/ped#1

**Comment by lchokhoe** [comment]
Intended behavior.

Will make this clear in the UG.
