### ISSUE TITLE
[PE-D] Cannot make empty detail

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T11-3/tp#157]
Detail always remains as "To add details, use the edit command". Is it possible to add a blank detail? Placeholder could be distracting because you have to read the entire detail description before realising that it is just a placeholder.

![Screenshot 2022-04-01 at 2.33.41 PM.png](https://raw.githubusercontent.com/chanyijuan/ped/main/files/04768857-3e0d-4e91-b95e-0806cd1ad9c6.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: chanyijuan/ped#2

**Comment by lchokhoe** [comment]
Suggestion for intended behaviour.

We can make the default string empty instead. Unsure if we can have both.

Not really a bug -> just decide whether we want empty String or a helpful message.
