### ISSUE TITLE
[PE-D] Typo under list command in UG: piroity

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T11-3/tp#159]
The UG specifies one of the sorting parameters as `piroity` I believe it is supposed to be priority.

![Screenshot 2022-04-01 at 2.35.43 PM.png](https://raw.githubusercontent.com/manu2002g/ped/main/files/554f62af-c716-4ae8-b977-0ec83e01f62f.png)Screenshot 2022-04-01 at 2.35.43 PM

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: manu2002g/ped#2

**Comment by lchokhoe** [comment]
Same as issue #161
