### ISSUE TITLE
[PE-D] `find` function does not match partial words.

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T11-3/tp#163]
A user might want to find an application but only remember part of the keyword.
I suggest that the `find` function matches partial words as well.

e.g. `find n/company` should return `CompanyA`.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: TypeDefinition/ped#7

**Comment by lchokhoe** [comment]
Same as issue #172
