### ISSUE TITLE
[PE-D] If 2 companies in the JSON save file has the same name, all data is deleted.

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T11-3/tp#167]
If the user manually edits the JSON save file, all data are deleted.

While this is something I noticed, I personally think that it is unfair to be penalised for as it is something the user would have to maliciously do.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: TypeDefinition/ped#8

**Comment by lchokhoe** [comment]
We can further test this behaviour.

Then a warning/caution against users on tempering with the internapply.json file could lead to loss of data which will be unrecoverable and that we won't be taking responsibility for such situations.

Warning should be related to duplicate applications!!!

Possibly related to issue #146

**Comment by laughingkid-sg** [comment]
Please read - https://github.com/nus-cs2103-AY2122S2/forum/issues/243

will add reminder in UG
