### ISSUE TITLE
[PE-D] Accepting invalid phone numbers

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T11-3/tp#168]
Minimum number of digits has been set to 3. This can result in invalid numbers
![Screenshot 2022-04-01 at 3.03.13 PM.png](https://raw.githubusercontent.com/rahulprasad01/ped/main/files/1af4e2a7-b844-41bb-93a2-fb6b50bbe472.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: rahulprasad01/ped#5

**Comment by lchokhoe** [comment]
"Good to fix" Bug.

No reason it shouldn't be the case that phone numbers are fixed to 8 digit number (this includes private phone numbers, company numbers and fax numbers). 

Only government bodies are able to have 5 or 6 digit numbers for communications.

The implications of making this the constraint would need further discussion.

Not a "real" bug. We will consider tweaking this but low.priority.
