### ISSUE TITLE
[PE-D] Date time missing add application -UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T11-3/tp#169]
Date time missing prefix and criteria missing in add application -UG
![Screenshot 2022-04-01 at 3.05.06 PM.png](https://raw.githubusercontent.com/rahulprasad01/ped/main/files/9b522bb9-9cc1-4505-8d41-104430273631.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: rahulprasad01/ped#6

**Comment by lchokhoe** [comment]
Good suggestion on an intended behaviour.

`add` is intended to not take in "idt/". Instead users can `edit` in their interview slot after the fact.

Unsure if we will change this due to feature freeze.

A note can be made on this constraint in the UG.

**Comment by laughingkid-sg** [comment]
The command /idt does not work with add command.

Reason: Interview dates are not given when you apply for an internship.

Will update this in FAQ.

@laughingkid-sg
