### ISSUE TITLE
[PE-D] Date in not fully visible

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T11-3/tp#170]
Date in not fully visible in result window.
![Screenshot 2022-04-01 at 3.06.48 PM.png](https://raw.githubusercontent.com/rahulprasad01/ped/main/files/29dd7de8-6ba9-4de4-bdfb-92163aea61da.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: rahulprasad01/ped#7

**Comment by lchokhoe** [comment]
Unsure if this is a bug.

The user might not have maximised the app on startup.

Maybe we can adjust the default height and width values to ensure that all information can be viewed on startup.

A note can also be added in the UG informing users to maximise the app window if the full information cannot be displayed.

More manual testing with different window sizes is needed to see when this becomes an issue.

Solution: set a default application window that  displays everything add text wrapping, Update UG with recommneded size
