### ISSUE TITLE
[PE-D] No way to delete existing priority tags.

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T11-3/tp#175]
`edit` command only replaces priority tags, but there is no way to remove priority tags.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: TypeDefinition/ped#10

**Comment by lchokhoe** [comment]
Good suggestion on an intended behaviour.

Due to feature freeze this is unlikely to be changed.

Maybe a additional caution note can be added in the UG for readers to know that all tags are "sticky" and cannot be removed.

**Comment by lchokhoe** [comment]
Same as issue #177
