### ISSUE TITLE
[PE-D] list name command breaks when lowercase names are added

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T11-3/tp#178]
When an application is added that has a company name that begins in lowercase, these applications always get sorted to the bottom of the list and not alphabetical order.

![Screenshot 2022-04-01 at 3.20.15 PM.png](https://raw.githubusercontent.com/manu2002g/ped/main/files/2f762f31-ff5f-41bc-9667-e59890433aa4.png)Screenshot 2022-04-01 at 3.20.15 PM

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: manu2002g/ped#6

**Comment by lchokhoe** [comment]
"Must fix" Bug.

One possible solution could be when comparing the "Name" field of 2 applications, first convert them to UPPER_CASE before making the comparison. 

This should directly address this bug without limiting users ability to input names in lower-case.
