### ISSUE TITLE
[PE-D] Misleading phrase in user guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T11-3/tp#180]
In this sentence, it seems to suggesting that `list` command does not take in any parameter, where in fact it does.

![image.png](https://raw.githubusercontent.com/1001mei/ped/main/files/55a73c19-dd68-4d06-b2de-25d41cf231ec.png)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: 1001mei/ped#8

**Comment by lchokhoe** [comment]
"Must fix" Bug.

Since `list` now takes in arguments for sorting feature to work.
