### ISSUE TITLE
[PE-D] Suggest change

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T11-3/tp#181]
Maybe changing `Find existing...` to `Finds existing...` would make the whole user guide looks more consistent.

![image.png](https://raw.githubusercontent.com/1001mei/ped/main/files/1297a189-b98c-4952-aaea-8cf766cfe412.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: 1001mei/ped#9

**Comment by lchokhoe** [comment]
"Good to fix" Bug.
