### ISSUE TITLE
[PE-D] Incorrect error message on add

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T11-3/tp#184]
When the add command is run with all the compulsory fields and the idt field, the error message that is thrown corresponds to the last field instead of telling the user that the idt field is invalid.

Eg: find j/engineer p/1244 a/aa e/e@e.ee n/name idt/02-02-2022 04:30 produces the error message
"Names should only contain alphanumeric characters and spaces, and it should not be blank"

![Screenshot 2022-04-01 at 5.44.26 PM.png](https://raw.githubusercontent.com/manu2002g/ped/main/files/362f7b3d-47af-4447-b6cd-e801966e4781.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: manu2002g/ped#8

**Comment by lchokhoe** [comment]
Reason for behaviour: "idt/" is not a recognised prefix for the "add" command. Hence, "name idt/02-02-2022 04:30" is being parsed as a single "n/" input which is triggering the error message.

I believe this is an intended behaviour

**Comment by joszx** [comment]
Maybe we can flesh out the UG and mention this intended behavior in FAQ

**Comment by laughingkid-sg** [comment]
The command `/idt` does not work with add command. 

Reason: Interview dates are not given when you apply for an internship. 

> Will update this in FAQ.

@laughingkid-sg
